services:
  app:
    build:
      context: .
    env_file: .env
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
